const ID = 'telys-battle-pass';
const defaults = () => ({title:"Nameless Honor",subtitle:"Rewards",levels:50,xpPerLevel:800,endDate:"",art:[],purchaseItem:"",purchaseQuantity:1,tabs:["Rewards","Missions","Rules"],rules:"Complete missions to gain battle pass EXP. Claim unlocked rewards once per track and level.",tracks:[{id:"gift",name:"Nameless Gift",rewards:[]},{id:"glory",name:"Nameless Glory",rewards:[]}],missions:[]});
const clone = x => foundry.utils.deepClone(x);
const esc = x => foundry.utils.escapeHTML(String(x ?? ''));
const world = () => {
 const c=clone(game.settings.get(ID,'config'));
 const old=c.tracks?.find(t=>t.id==='honor');
 const glory=c.tracks?.find(t=>t.id==='glory') || {id:'glory',name:'Nameless Glory',rewards:[]};
 glory.rewards=(glory.rewards||[]).map(r=>({...r,slot:Number(r.slot)||1}));
 // Preserve existing Honor rewards in Glory's second slot when upgrading old worlds.
 for(const r of old?.rewards||[])if(!glory.rewards.some(g=>Number(g.level)===Number(r.level)&&Number(g.slot)===2))glory.rewards.push({...r,slot:2});
 c.tracks=[c.tracks?.find(t=>t.id==='gift')||{id:'gift',name:'Nameless Gift',rewards:[]},glory];
 return c;
};
const progress = user => {const p=clone(user.getFlag(ID,'progress') ?? {xp:0,completed:{},claimed:{},glory:false});p.glory ||= Boolean(p.honor);return p};
const level = (p,c) => Math.min(c.levels, Math.floor(p.xp/c.xpPerLevel)+1);
const users = () => game.users.filter(u=>!u.isGM);
const itemFor = (actor,uuid) => actor?.items.find(i=>i.uuid===uuid || i.id===uuid.split('.').at(-1) || i.getFlag(ID,'sourceUuid')===uuid);
const activeActor = user => user.character || game.actors.find(a=>a.hasPlayerOwner && a.testUserPermission(user,'OWNER'));
async function resolveItem(uuid){try{return await fromUuid(uuid)}catch{return null}}
async function award(user,mission){const p=progress(user);if(p.completed[mission.id]) return; p.completed[mission.id]=true;p.xp+=Math.max(0,Number(mission.xp)||0);await user.setFlag(ID,'progress',p)}
async function purchase(user){if(!game.user.isGM)throw Error('GM only');const c=world(),actor=activeActor(user),uuid=c.purchaseItem,qty=Math.max(1,Number(c.purchaseQuantity)||1),item=itemFor(actor,uuid);if(!uuid||!item||Number(item.system?.quantity||0)<qty)throw Error('Player lacks the required purchase item or assigned character.');const p=progress(user);if(p.glory)throw Error('Already unlocked');await item.update({'system.quantity':Number(item.system.quantity)-qty});p.glory=true;await user.setFlag(ID,'progress',p)}
async function claim(user,track,lv,slot){if(!game.user.isGM)throw Error('GM only');const c=world(),p=progress(user),reward=c.tracks.find(t=>t.id===track)?.rewards?.find(r=>Number(r.level)===lv&&(track==='gift'||Number(r.slot||1)===slot));const key=`${track}:${lv}:${slot}`;if(!reward||level(p,c)<lv||(p.claimed[key]||slot===1&&p.claimed[`${track}:${lv}`])||(!p.glory&&track==='glory'))throw Error('Reward unavailable');const actor=activeActor(user);if(!actor)throw Error('Player has no assigned character');const item=await resolveItem(reward.uuid);if(!item||item.documentName!=='Item')throw Error('Reward item is missing');const data=item.toObject();delete data._id;data.system??={};data.system.quantity=Math.max(1,Number(reward.quantity)||1);await actor.createEmbeddedDocuments('Item',[data]);p.claimed[key]=true;await user.setFlag(ID,'progress',p)}
class BattlePass extends foundry.applications.api.ApplicationV2 {
 static DEFAULT_OPTIONS={id:'telys-battle-pass-window',window:{title:"Tely's Battle Pass",resizable:true},position:{width:1180,height:760},classes:['tely-bp'],actions:{}};
 tab='Rewards'; selected=null; slide=0;
 async _renderHTML(){const c=world(), user=this.selected&&game.users.get(this.selected)||(game.user.isGM?users()[0]:game.user)||game.user,p=progress(user),lv=level(p,c), remaining=c.endDate?Math.max(0,Math.ceil((new Date(c.endDate)-Date.now())/86400000)):null;return `<div class="bp-shell"><header><strong>${esc(c.title)}</strong><span>${esc(c.subtitle)}</span><span>Level ${lv} · ${p.xp} EXP · ${p.xp%c.xpPerLevel}/${c.xpPerLevel}</span>${remaining===null?'':`<span>${remaining} days left</span>`}${game.user.isGM?`<select data-role="user">${users().map(u=>`<option value="${u.id}" ${u.id===user.id?'selected':''}>${esc(u.name)}</option>`).join('')}</select><button data-do="config">Configure</button>`:''}</header><nav>${c.tabs.map(t=>`<button data-tab="${esc(t)}" class="${this.tab===t?'active':''}">${esc(t)}</button>`).join('')}</nav><main>${this.tab===c.tabs[0]?`<section class="bp-rewards"><div class="bp-tracks">${c.tracks.map(t=>`<div class="bp-track ${t.id==='glory'?'bp-glory':''}"><h2>${esc(t.name)} ${t.id==='glory'&&!p.glory?'<span>Locked</span>':''}</h2><div class="bp-row">${Array.from({length:c.levels},(_,i)=>{const n=i+1,slots=t.id==='glory'?[1,2]:[1];return `<article><b>Lv. ${n}</b><div class="bp-slots">${slots.map(slot=>{const r=t.rewards.find(r=>Number(r.level)===n&&(t.id==='gift'||Number(r.slot||1)===slot)),claimed=p.claimed[`${t.id}:${n}:${slot}`]||p.claimed[`${t.id}:${n}`]&&slot===1;return `<div class="bp-slot ${claimed?'claimed':''}">${r?`<img src="${esc(r.img||'icons/svg/item-bag.svg')}"><small>${esc(r.name)} ×${esc(r.quantity||1)}</small>`:'<small>—</small>'}${claimed?'<em>✓ Claimed</em>':game.user.isGM&&r&&lv>=n&&(t.id==='gift'||p.glory)?`<button data-do="claim" data-track="${t.id}" data-level="${n}" data-slot="${slot}">Grant</button>`:''}</div>`}).join('')}</div></article>`}).join('')}</div></div>`).join('')}</div><aside><h2>Featured rewards</h2>${c.art.length?`<img class="bp-feature" src="${esc(c.art[this.slide%c.art.length])}"><div>${c.art.map((_,i)=>`<button data-do="slide" data-index="${i}" class="${i===this.slide%c.art.length?'active':''}">●</button>`).join('')}</div>`:'<p>GM can add preview images in Configure.</p>'}${game.user.isGM&&!p.glory?`<button data-do="purchase" data-tier="glory">Unlock Nameless Glory</button>`:''}</aside></section>`:this.tab===c.tabs[1]?`<section class="bp-missions">${c.missions.map(m=>`<article><div><b>${esc(m.title)}</b><p>${esc(m.description)}</p><small>+${esc(m.xp)} EXP</small></div>${p.completed[m.id]?'<strong class="bp-done">✓ Complete</strong>':game.user.isGM?`<button data-do="complete" data-id="${m.id}">Mark complete</button>`:'<span>In progress</span>'}</article>`).join('')||'<p>No missions configured.</p>'}</section>`:`<section class="bp-rules">${esc(c.rules).replaceAll('\n','<br>')}</section>`}</main></div>`}
 _replaceHTML(result,content){content.replaceChildren();content.innerHTML=result}
 async _onRender(){const el=this.element;el.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{this.tab=b.dataset.tab;this.render()});el.querySelector('[data-role="user"]')?.addEventListener('change',e=>{this.selected=e.target.value;this.render()});el.querySelectorAll('[data-do]').forEach(b=>b.onclick=async()=>{try{const a=b.dataset.do,u=game.users.get(this.selected)||game.user;if(a==='config')new Config().render(true);if(a==='slide'){this.slide=Number(b.dataset.index);this.render()}if(a==='complete'){const m=world().missions.find(x=>x.id===b.dataset.id);if(m)await award(u,m)}if(a==='claim')await claim(u,b.dataset.track,Number(b.dataset.level),Number(b.dataset.slot));if(a==='purchase')await purchase(u);if(['complete','claim','purchase'].includes(a))this.render()}catch(e){ui.notifications.error(e.message)}});clearInterval(this.timer);this.timer=setInterval(()=>{if(!this.element?.isConnected){clearInterval(this.timer);return}if(this.tab===world().tabs[0]&&world().art.length>1){this.slide++;this.render()}},5000)}
 async close(options){clearInterval(this.timer);return super.close(options)}
}
class Config extends foundry.applications.api.ApplicationV2{
 static DEFAULT_OPTIONS={id:'tely-bp-config',window:{title:'Battle Pass Configuration',resizable:true},position:{width:850,height:800},classes:['tely-bp']};
 async _renderHTML(){const c=world();return `<div class="bp-config"><p>Drop Item documents onto reward and purchase fields. Drop an image from the File Browser onto the preview box, or enter a PNG path.</p><label>Title <input name="title" value="${esc(c.title)}"></label><label>Subtitle <input name="subtitle" value="${esc(c.subtitle)}"></label><label>Max level <input name="levels" type="number" min="1" value="${c.levels}"></label><label>EXP per level <input name="xpPerLevel" type="number" min="1" value="${c.xpPerLevel}"></label><label>End date <input name="endDate" type="datetime-local" value="${esc(c.endDate)}"></label><label>Tab names, separated by | <input name="tabs" value="${esc(c.tabs.join(' | '))}"></label><label>Rules <textarea name="rules">${esc(c.rules)}</textarea></label><h3>Nameless Glory purchase</h3><label>Required loot item UUID (drop Item) <input name="purchaseItem" value="${esc(c.purchaseItem)}"></label><label>Quantity <input name="purchaseQuantity" type="number" min="1" value="${c.purchaseQuantity}"></label><h3>Featured preview images (one PNG path per line)</h3><textarea name="art" class="bp-drop-img">${esc(c.art.join('\n'))}</textarea><h3>Tracks and rewards</h3>${c.tracks.map(t=>`<section class="bp-edit-track" data-track="${t.id}"><label>${esc(t.id)} display name <input class="track-name" value="${esc(t.name)}"></label><div class="reward-list">${t.rewards.map(r=>this.rewardRow(r)).join('')}</div><button data-add="reward">Add reward</button></section>`).join('')}<h3>Missions</h3><div class="mission-list">${c.missions.map(m=>this.missionRow(m)).join('')}</div><button data-add="mission">Add mission</button><footer><button data-save>Save configuration</button></footer></div>`}
 rewardRow(r={}){return `<div class="bp-edit-row reward" data-id="${esc(r.id||foundry.utils.randomID())}"><input class="r-level" type="number" min="1" placeholder="Level" value="${esc(r.level||'')}"><select class="r-slot"><option value="1" ${Number(r.slot||1)===1?'selected':''}>Slot 1</option><option value="2" ${Number(r.slot)===2?'selected':''}>Slot 2</option></select><input class="r-uuid" placeholder="Drop Item / UUID" value="${esc(r.uuid||'')}"><input class="r-name" placeholder="Label" value="${esc(r.name||'')}"><input class="r-img" placeholder="Icon path" value="${esc(r.img||'')}"><input class="r-qty" type="number" min="1" value="${esc(r.quantity||1)}"><button data-remove>×</button></div>`}
 missionRow(m={}){return `<div class="bp-edit-row mission" data-id="${esc(m.id||foundry.utils.randomID())}"><input class="m-title" placeholder="Mission title" value="${esc(m.title||'')}"><input class="m-desc" placeholder="Description" value="${esc(m.description||'')}"><input class="m-xp" type="number" min="0" placeholder="EXP" value="${esc(m.xp||0)}"><button data-remove>×</button></div>`}
 _replaceHTML(result,content){content.replaceChildren();content.innerHTML=result}
 _onRender(){const e=this.element;e.querySelectorAll('[data-add]').forEach(b=>b.onclick=()=>{const box=b.dataset.add==='reward'?b.closest('section').querySelector('.reward-list'):e.querySelector('.mission-list');box.insertAdjacentHTML('beforeend',b.dataset.add==='reward'?this.rewardRow():this.missionRow())});e.onclick=ev=>{if(ev.target.matches('[data-remove]'))ev.target.closest('.bp-edit-row').remove()};e.ondragover=ev=>{if(ev.target.matches('input,textarea'))ev.preventDefault()};e.ondrop=async ev=>{if(!ev.target.matches('input,textarea'))return;ev.preventDefault();let data;try{data=TextEditor.getDragEventData(ev)}catch{return}if(data?.type==='Item'){const item=await resolveItem(data.uuid);if(!item)return;ev.target.value=data.uuid;if(ev.target.classList.contains('r-uuid')){const row=ev.target.closest('.reward');row.querySelector('.r-name').value=item.name;row.querySelector('.r-img').value=item.img}}else if(data?.type==='Tile'||data?.type==='File'){const src=data.src||data.path;if(src)ev.target.value+=ev.target.value?'\n'+src:src}};e.querySelector('[data-save]').onclick=async()=>{const val=n=>e.querySelector(`[name="${n}"]`).value.trim(),c=world();c.title=val('title');c.subtitle=val('subtitle');c.levels=Math.max(1,Number(val('levels'))||1);c.xpPerLevel=Math.max(1,Number(val('xpPerLevel'))||1);c.endDate=val('endDate');c.tabs=val('tabs').split('|').map(x=>x.trim()).slice(0,3);while(c.tabs.length<3)c.tabs.push(['Rewards','Missions','Rules'][c.tabs.length]);c.rules=val('rules');c.purchaseItem=val('purchaseItem');c.purchaseQuantity=Math.max(1,Number(val('purchaseQuantity'))||1);c.art=val('art').split('\n').map(x=>x.trim()).filter(Boolean);c.tracks=e.querySelectorAll('.bp-edit-track');c.tracks=Array.from(c.tracks,t=>({id:t.dataset.track,name:t.querySelector('.track-name').value.trim(),rewards:Array.from(t.querySelectorAll('.reward'),r=>({id:r.dataset.id,level:Number(r.querySelector('.r-level').value),slot:t.dataset.track==='gift'?1:Number(r.querySelector('.r-slot').value),uuid:r.querySelector('.r-uuid').value.trim(),name:r.querySelector('.r-name').value.trim(),img:r.querySelector('.r-img').value.trim(),quantity:Math.max(1,Number(r.querySelector('.r-qty').value)||1)})).filter(r=>r.level&&r.uuid)}));c.missions=Array.from(e.querySelectorAll('.mission'),m=>({id:m.dataset.id,title:m.querySelector('.m-title').value.trim(),description:m.querySelector('.m-desc').value.trim(),xp:Math.max(0,Number(m.querySelector('.m-xp').value)||0)})).filter(m=>m.title);for(const t of c.tracks){const seen=new Set();for(const r of t.rewards){if(r.level>c.levels){ui.notifications.error(`Reward level ${r.level} exceeds the maximum level`);return};const key=`${r.level}:${r.slot}`;if(seen.has(key)){ui.notifications.error(`Duplicate reward at ${t.name} level ${r.level}, slot ${r.slot}`);return};seen.add(key)}}await game.settings.set(ID,'config',c);ui.notifications.info('Battle pass saved');this.close();window.TelyBattlePass.open()}}
}
Hooks.once('init',()=>{game.settings.register(ID,'config',{name:'Battle Pass Configuration',scope:'world',config:false,type:Object,default:defaults()});window.TelyBattlePass={open:()=>{new BattlePass().render(true)},configure:()=>{if(game.user.isGM)new Config().render(true)}}});
Hooks.on('getSceneControlButtons',controls=>{controls.push({name:'tely-battle-pass',title:"Tely's Battle Pass",icon:'fas fa-gift',visible:true,tools:[{name:'open',title:'Open Battle Pass',icon:'fas fa-gift',button:true,onClick:()=>window.TelyBattlePass.open()}],activeTool:'open'})});
Hooks.once('ready',()=>{const button=document.createElement('button');button.id='tely-bp-launch';button.title="Tely's Battle Pass";button.innerHTML='<i class="fas fa-gift"></i>';button.onclick=()=>window.TelyBattlePass.open();document.body.append(button)});
Hooks.on('updateSetting',setting=>{if(setting.key===`${ID}.config`)document.querySelector('.tely-bp')&&window.TelyBattlePass.open()});
